/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1-dev-2690-gb8eefd0061"
#endif /* AVUTIL_FFVERSION_H */
