self-hosted-runner:
  labels:
    - macos-13
    - pi4
    - pi5
    - ubuntu-large
    - ubuntu-large-arm
    - ubuntu-small-arm
    - buildjet-2vcpu-ubuntu-2204
    - buildjet-4vcpu-ubuntu-2204
    - buildjet-8vcpu-ubuntu-2204
    - buildjet-16vcpu-ubuntu-2204
    - buildjet-32vcpu-ubuntu-2204
    - buildjet-2vcpu-ubuntu-2204-arm
    - buildjet-4vcpu-ubuntu-2204-arm
    - buildjet-8vcpu-ubuntu-2204-arm
    - buildjet-16vcpu-ubuntu-2204-arm
    - buildjet-32vcpu-ubuntu-2204-arm
    - buildjet-pinned-location_de_arm
    # Include windows-2025 as a "self-hosted" runner because our actionlint version is so
    # old, that it's unaware this runner label exists. See
    # https://viam.atlassian.net/browse/RSDK-11699.
    - windows-2025
