min_version = '2026.8.16'

[tools]
go = "1.25"
golangci-lint = "2.9.0"
# It would be nice to make ruby lazy but at time of writing mise can't figure
# out that it needs to install ruby before any gem tools and the whole install
# fails. Installing ruby only takes ~3s on an amd64 linux machine anyway.
ruby = "4.0.6"

[tools.upx]
version = "5.2.1"
lazy = true

[tools."go:github.com/viamrobotics/canon"]
version = "latest"
lazy = true
lazy_bins = ['canon']

[tools."gem:license_finder"]
version = "7.2.1"
lazy = true
lazy_bins = ['license_finder']

[tasks.lint-go]
alias = "lint"
description = 'Lint and format go code'
usage = '''
flag "-n --dry-run" default=#false env="LINT_DRY_RUN" help="Print diffs rather than automatically applying fixes"
'''
run = '''
set -x
go mod tidy{% if usage.dry_run %} -diff{% endif %}|| result=$?
golangci-lint run{% if env.CI %} -v{% endif %}{% if not usage.dry_run %} --fix{% endif %} || result=$?
golangci-lint fmt{% if env.CI %} -v{% endif %}{% if usage.dry_run %} --diff{% endif %} || result=$?
./etc/lint_register_apis.sh || result=$?
exit ${result:-0}
'''

[tasks.license-check]
run = [
	'license_finder version',
	'license_finder',
]
