[tools]
golangci-lint = "2.9.0"

[tasks.lint-go]
alias = "lint"
run = [
  'go mod tidy',
  'golangci-lint run',
  './etc/lint_register_apis.sh',
]

[tasks.fix-go]
alias = "fix"
run = [
  'go mod tidy',
  'golangci-lint run --fix',
  'golangci-lint fmt',
]