min_version = '2026.8.16'

[tools]
"gem:license_finder" = "7.2.1"
go = "1.25"
"go:github.com/viamrobotics/canon" = "latest"
golangci-lint = "2.9.0"
ruby = "4.0.6"
upx = "5.2.1"

[tasks.lint-go]
alias = "lint"
description = 'Lint and format go code'
usage = '''
flag "-n --dry-run" default=#false env="LINT_DRY_RUN" help="Print diffs rather than automatically applying fixes"
'''
run = '''
set -x
go mod tidy{% if usage.dry_run %} -diff{% endif %}|| result=$?
golangci-lint run{% if env.CI %} -v{% endif %}{% if not usage.dry_run %} --fix{% endif %} || result=$?
golangci-lint fmt{% if env.CI %} -v{% endif %}{% if usage.dry_run %} --diff{% endif %} || result=$?
./etc/lint_register_apis.sh || result=$?
exit ${result:-0}
'''

[tasks.license-check]
run = [
  'license_finder version',
  'license_finder',
]
