[workspace]
authors = ["James Otting <james@viam.com>"]
channels = ["http://packages.viam.com/conda/", "conda-forge"]
name = "rdk"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

[dependencies]
go = ">=1.24.5,<2"
pkg-config = ">=0.29.2,<0.30"
make = ">=4.4.1,<5"
binutils = ">=2.44,<3"
x264 = ">=1!164.3095,<1!165"
nlopt = ">=2.10.0,<3"
bash = ">=5.2.37,<6"
gcc = ">=15.1.0,<15.2"
git = ">=2.51.0,<3"
