//go:build linux && (arm64 || arm)

// Package piimpl contains the implementation of a supported Raspberry Pi board.
package piimpl

// #include <stdlib.h>
// #include <pigpio.h>
// #include "pi.h"
// #cgo LDFLAGS: -lpigpio
import "C"

import "github.com/pkg/errors"

// PiGPIOErrorMap maps the error codes to the human readable error names. This can be found at the pigpio C interface.
var PiGPIOErrorMap = map[int]string{
	C.PI_INIT_FAILED:      "PI_INIT_FAILED: gpioInitialise failed",
	C.PI_BAD_USER_GPIO:    "PI_BAD_USER_GPIO: GPIO not 0-31",
	C.PI_BAD_GPIO:         "PI_BAD_GPIO: GPIO not 0-53",
	C.PI_BAD_MODE:         "PI_BAD_MODE: mode not 0-7",
	C.PI_BAD_LEVEL:        "PI_BAD_LEVEL: level not 0-1",
	C.PI_BAD_PUD:          "PI_BAD_PUD: pud not 0-2",
	C.PI_BAD_PULSEWIDTH:   "PI_BAD_PULSEWIDTH: pulsewidth not 0 or 500-2500",
	C.PI_BAD_DUTYCYCLE:    "PI_BAD_DUTYCYCLE: dutycycle outside set range",
	C.PI_BAD_TIMER:        "PI_BAD_TIMER: timer not 0-9",
	C.PI_BAD_MS:           "PI_BAD_MS: ms not 10-60000",
	C.PI_BAD_TIMETYPE:     "PI_BAD_TIMETYPE: timetype not 0-1",
	C.PI_BAD_SECONDS:      "PI_BAD_SECONDS: seconds < 0",
	C.PI_BAD_MICROS:       "PI_BAD_MICROS: micros not 0-999999",
	C.PI_TIMER_FAILED:     "PI_TIMER_FAILED: gpioSetTimerFunc failed",
	C.PI_BAD_WDOG_TIMEOUT: "PI_BAD_WDOG_TIMEOUT: timeout not 0-60000",
	C.PI_NO_ALERT_FUNC:    "PI_NO_ALERT_FUNC: DEPRECATED",
	C.PI_BAD_CLK_PERIPH:   "PI_BAD_CLK_PERIPH: clock peripheral not 0-1",
	C.PI_BAD_CLK_SOURCE:   "PI_BAD_CLK_SOURCE: DEPRECATED",
	C.PI_BAD_CLK_MICROS:   "PI_BAD_CLK_MICROS: clock micros not 1, 2, 4, 5, 8, or 10",
	C.PI_BAD_BUF_MILLIS:   "PI_BAD_BUF_MILLIS: buf millis not 100-10000",
	C.PI_BAD_DUTYRANGE:    "PI_BAD_DUTYRANGE: dutycycle range not 25-40000",
	C.PI_BAD_SIGNUM:       "PI_BAD_SIGNUM: signum not 0-63",
	C.PI_BAD_PATHNAME:     "PI_BAD_PATHNAME: can't open pathname",
	C.PI_NO_HANDLE:        "PI_NO_HANDLE: no handle available",
	C.PI_BAD_HANDLE:       "PI_BAD_HANDLE: unknown handle",
	C.PI_BAD_IF_FLAGS:     "PI_BAD_IF_FLAGS: ifFlags > 4",
	C.PI_BAD_CHANNEL:      "PI_BAD_CHANNEL or PI_BAD_PRIM_CHANNEL: DMA channel not 0-15 OR DMA primary channel not 0-15",
	C.PI_BAD_SOCKET_PORT:  "PI_BAD_SOCKET_PORT: socket port not 1024-32000",
	C.PI_BAD_FIFO_COMMAND: "PI_BAD_FIFO_COMMAND: unrecognized fifo command",
	C.PI_BAD_SECO_CHANNEL: "PI_BAD_SECO_CHANNEL: DMA secondary channel not 0-15",
	C.PI_NOT_INITIALISED:  "PI_NOT_INITIALISED: function called before gpioInitialise",
	C.PI_INITIALISED:      "PI_INITIALISED: function called after gpioInitialise",
	C.PI_BAD_WAVE_MODE:    "PI_BAD_WAVE_MODE: waveform mode not 0-3",
	C.PI_BAD_CFG_INTERNAL: "PI_BAD_CFG_INTERNAL: bad parameter in gpioCfgInternals call",
	C.PI_BAD_WAVE_BAUD:    "PI_BAD_WAVE_BAUD: baud rate not 50-250K(RX)/50-1M(TX)",
	C.PI_TOO_MANY_PULSES:  "PI_TOO_MANY_PULSES: waveform has too many pulses",
	C.PI_TOO_MANY_CHARS:   "PI_TOO_MANY_CHARS: waveform has too many chars",
	C.PI_NOT_SERIAL_GPIO:  "PI_NOT_SERIAL_GPIO: no bit bang serial read on GPIO",
	C.PI_BAD_SERIAL_STRUC: "PI_BAD_SERIAL_STRUC: bad (null) serial structure parameter",
	C.PI_BAD_SERIAL_BUF:   "PI_BAD_SERIAL_BUF: bad (null) serial buf parameter",
	C.PI_NOT_PERMITTED:    "PI_NOT_PERMITTED: GPIO operation not permitted",
	C.PI_SOME_PERMITTED:   "PI_SOME_PERMITTED: one or more GPIO not permitted",
	C.PI_BAD_WVSC_COMMND:  "PI_BAD_WVSC_COMMND: bad WVSC subcommand",
	C.PI_BAD_WVSM_COMMND:  "PI_BAD_WVSM_COMMND: bad WVSM subcommand",
	C.PI_BAD_WVSP_COMMND:  "PI_BAD_WVSP_COMMND: bad WVSP subcommand",
	C.PI_BAD_PULSELEN:     "PI_BAD_PULSELEN: trigger pulse length not 1-100",
	C.PI_BAD_SCRIPT:       "PI_BAD_SCRIPT: invalid script",
	C.PI_BAD_SCRIPT_ID:    "PI_BAD_SCRIPT_ID: unknown script id",
	C.PI_BAD_SER_OFFSET:   "PI_BAD_SER_OFFSET: add serial data offset > 30 minutes",
	C.PI_GPIO_IN_USE:      "PI_GPIO_IN_USE: GPIO already in use",
	C.PI_BAD_SERIAL_COUNT: "PI_BAD_SERIAL_COUNT: must read at least a byte at a time",
	C.PI_BAD_PARAM_NUM:    "PI_BAD_PARAM_NUM: script parameter id not 0-9",
	C.PI_DUP_TAG:          "PI_DUP_TAG: script has duplicate tag",
	C.PI_TOO_MANY_TAGS:    "PI_TOO_MANY_TAGS: script has too many tags",
	C.PI_BAD_SCRIPT_CMD:   "PI_BAD_SCRIPT_CMD: illegal script command",
	C.PI_BAD_VAR_NUM:      "PI_BAD_VAR_NUM: script variable id not 0-149",
	C.PI_NO_SCRIPT_ROOM:   "PI_NO_SCRIPT_ROOM: no more room for scripts",
	C.PI_NO_MEMORY:        "PI_NO_MEMORY: can't allocate temporary memory",
	C.PI_SOCK_READ_FAILED: "PI_SOCK_READ_FAILED: socket read failed",
	C.PI_SOCK_WRIT_FAILED: "PI_SOCK_WRIT_FAILED: socket write failed",
	C.PI_TOO_MANY_PARAM:   "PI_TOO_MANY_PARAM: too many script parameters (> 10)",
	C.PI_SCRIPT_NOT_READY: "PI_SCRIPT_NOT_READY: script initialising",
	C.PI_BAD_TAG:          "PI_BAD_TAG: script has unresolved tag",
	C.PI_BAD_MICS_DELAY:   "PI_BAD_MICS_DELAY: bad MICS delay (too large)",
	C.PI_BAD_MILS_DELAY:   "PI_BAD_MILS_DELAY: bad MILS delay (too large)",
	C.PI_BAD_WAVE_ID:      "PI_BAD_WAVE_ID: non existent wave id",
	C.PI_TOO_MANY_CBS:     "PI_TOO_MANY_CBS: No more CBs for waveform",
	C.PI_TOO_MANY_OOL:     "PI_TOO_MANY_OOL: No more OOL for waveform",
	C.PI_EMPTY_WAVEFORM:   "PI_EMPTY_WAVEFORM: attempt to create an empty waveform",
	C.PI_NO_WAVEFORM_ID:   "PI_NO_WAVEFORM_ID: no more waveforms",
	C.PI_I2C_OPEN_FAILED:  "PI_I2C_OPEN_FAILED: can't open I2C device",
	C.PI_SER_OPEN_FAILED:  "PI_SER_OPEN_FAILED: can't open serial device",
	C.PI_SPI_OPEN_FAILED:  "PI_SPI_OPEN_FAILED: can't open SPI device",
	C.PI_BAD_I2C_BUS:      "PI_BAD_I2C_BUS: bad I2C bus",
	C.PI_BAD_I2C_ADDR:     "PI_BAD_I2C_ADDR: bad I2C address",
	C.PI_BAD_SPI_CHANNEL:  "PI_BAD_SPI_CHANNEL: bad SPI channel",
	C.PI_BAD_FLAGS:        "PI_BAD_FLAGS: bad i2c/spi/ser open flags",
	C.PI_BAD_SPI_SPEED:    "PI_BAD_SPI_SPEED: bad SPI speed",
	C.PI_BAD_SER_DEVICE:   "PI_BAD_SER_DEVICE: bad serial device name",
	C.PI_BAD_SER_SPEED:    "PI_BAD_SER_SPEED: bad serial baud rate",
	C.PI_BAD_PARAM:        "PI_BAD_PARAM: bad i2c/spi/ser parameter",
	C.PI_I2C_WRITE_FAILED: "PI_I2C_WRITE_FAILED: i2c write failed",
	C.PI_I2C_READ_FAILED:  "PI_I2C_READ_FAILED: i2c read failed",
	C.PI_BAD_SPI_COUNT:    "PI_BAD_SPI_COUNT: bad SPI count",
	C.PI_SER_WRITE_FAILED: "PI_SER_WRITE_FAILED: ser write failed",
	C.PI_SER_READ_FAILED:  "PI_SER_READ_FAILED: ser read failed",
	C.PI_SER_READ_NO_DATA: "PI_SER_READ_NO_DATA: ser read no data available",
	C.PI_UNKNOWN_COMMAND:  "PI_UNKNOWN_COMMAND: unknown command",
	C.PI_SPI_XFER_FAILED:  "PI_SPI_XFER_FAILED: spi xfer/read/write failed",
	C.PI_BAD_POINTER:      "PI_BAD_POINTER: bad (NULL) pointer",
	C.PI_NO_AUX_SPI:       "PI_NO_AUX_SPI: no auxiliary SPI on Pi A or B",
	C.PI_NOT_PWM_GPIO:     "PI_NOT_PWM_GPIO: GPIO is not in use for PWM",
	C.PI_NOT_SERVO_GPI:    "PI_NOT_SERVO_GPI: GPIO is not in use for servo pulses",
	C.PI_NOT_HCLK_GPIO:    "PI_NOT_HCLK_GPIO: GPIO has no hardware clock",
	C.PI_NOT_HPWM_GPIO:    "PI_NOT_HPWM_GPIO: GPIO has no hardware PWM",
	C.PI_BAD_HPWM_FREQ:    "PI_BAD_HPWM_FREQ: invalid hardware PWM frequency",
	C.PI_BAD_HPWM_DUTY:    "PI_BAD_HPWM_DUTY: hardware PWM dutycycle not 0-1M",
	C.PI_BAD_HCLK_FREQ:    "PI_BAD_HCLK_FREQ: invalid hardware clock frequency",
	C.PI_BAD_HCLK_PASS:    "PI_BAD_HCLK_PASS: need password to use hardware clock 1",
	C.PI_HPWM_ILLEGAL:     "PI_HPWM_ILLEGAL: illegal, PWM in use for main clock",
	C.PI_BAD_DATABITS:     "PI_BAD_DATABITS: serial data bits not 1-32",
	C.PI_BAD_STOPBITS:     "PI_BAD_STOPBITS: serial (half) stop bits not 2-8",
	C.PI_MSG_TOOBIG:       "PI_MSG_TOOBIG: socket/pipe message too big",
	C.PI_BAD_MALLOC_MODE:  "PI_BAD_MALLOC_MODE: bad memory allocation mode",
	C.PI_TOO_MANY_SEGS:    "PI_TOO_MANY_SEGS: too many I2C transaction segments",
	C.PI_BAD_I2C_SEG:      "PI_BAD_I2C_SEG: an I2C transaction segment failed",
	C.PI_BAD_SMBUS_CMD:    "PI_BAD_SMBUS_CMD: SMBus command not supported by driver",
	C.PI_NOT_I2C_GPIO:     "PI_NOT_I2C_GPIO: no bit bang I2C in progress on GPIO",
	C.PI_BAD_I2C_WLEN:     "PI_BAD_I2C_WLEN: bad I2C write length",
	C.PI_BAD_I2C_RLEN:     "PI_BAD_I2C_RLEN: bad I2C read length",
	C.PI_BAD_I2C_CMD:      "PI_BAD_I2C_CMD: bad I2C command",
	C.PI_BAD_I2C_BAUD:     "PI_BAD_I2C_BAUD: bad I2C baud rate, not 50-500k",
	C.PI_CHAIN_LOOP_CNT:   "PI_CHAIN_LOOP_CNT: bad chain loop count",
	C.PI_BAD_CHAIN_LOOP:   "PI_BAD_CHAIN_LOOP: empty chain loop",
	C.PI_CHAIN_COUNTER:    "PI_CHAIN_COUNTER: too many chain counters",
	C.PI_BAD_CHAIN_CMD:    "PI_BAD_CHAIN_CMD: bad chain command",
	C.PI_BAD_CHAIN_DELAY:  "PI_BAD_CHAIN_DELAY: bad chain delay micros",
	C.PI_CHAIN_NESTING:    "PI_CHAIN_NESTING: chain counters nested too deeply",
	C.PI_CHAIN_TOO_BIG:    "PI_CHAIN_TOO_BIG: chain is too long",
	C.PI_DEPRECATED:       "PI_DEPRECATED: deprecated function removed",
	C.PI_BAD_SER_INVERT:   "PI_BAD_SER_INVERT: bit bang serial invert not 0 or 1",
	C.PI_BAD_EDGE:         "PI_BAD_EDGE: bad ISR edge value, not 0-2",
	C.PI_BAD_ISR_INIT:     "PI_BAD_ISR_INIT: bad ISR initialisation",
	C.PI_BAD_FOREVER:      "PI_BAD_FOREVER: loop forever must be last command",
	C.PI_BAD_FILTER:       "PI_BAD_FILTER: bad filter parameter",
	C.PI_BAD_PAD:          "PI_BAD_PAD: bad pad number",
	C.PI_BAD_STRENGTH:     "PI_BAD_STRENGTH: bad pad drive strength",
	C.PI_FIL_OPEN_FAILED:  "PI_FIL_OPEN_FAILED: file open failed",
	C.PI_BAD_FILE_MODE:    "PI_BAD_FILE_MODE: bad file mode",
	C.PI_BAD_FILE_FLAG:    "PI_BAD_FILE_FLAG: bad file flag",
	C.PI_BAD_FILE_READ:    "PI_BAD_FILE_READ: bad file read",
	C.PI_BAD_FILE_WRITE:   "PI_BAD_FILE_WRITE: bad file write",
	C.PI_FILE_NOT_ROPEN:   "PI_FILE_NOT_ROPEN: file not open for read",
	C.PI_FILE_NOT_WOPEN:   "PI_FILE_NOT_WOPEN: file not open for write",
	C.PI_BAD_FILE_SEEK:    "PI_BAD_FILE_SEEK: bad file seek",
	C.PI_NO_FILE_MATCH:    "PI_NO_FILE_MATCH: no files match pattern",
	C.PI_NO_FILE_ACCESS:   "PI_NO_FILE_ACCESS: no permission to access file",
	C.PI_FILE_IS_A_DIR:    "PI_FILE_IS_A_DIR: file is a directory",
	C.PI_BAD_SHELL_STATUS: "PI_BAD_SHELL_STATUS: bad shell return status",
	C.PI_BAD_SCRIPT_NAME:  "PI_BAD_SCRIPT_NAME: bad script name",
	C.PI_BAD_SPI_BAUD:     "PI_BAD_SPI_BAUD: bad SPI baud rate, not 50-500k",
	C.PI_NOT_SPI_GPIO:     "PI_NOT_SPI_GPIO: no bit bang SPI in progress on GPIO",
	C.PI_BAD_EVENT_ID:     "PI_BAD_EVENT_IDD: bad event id",
	C.PI_CMD_INTERRUPTED:  "PI_CMD_INTERRUPTED: Used by Python",
	C.PI_NOT_ON_BCM2711:   "PI_NOT_ON_BCM2711: not available on BCM2711",
	C.PI_ONLY_ON_BCM2711:  "PI_ONLY_ON_BCM2711: only available on BCM271",
	C.PI_PIGIF_ERR_0:      "PI_PIGIF_ERR_0",
	C.PI_PIGIF_ERR_99:     "PI_PIGIF_ERR_99",
	C.PI_CUSTOM_ERR_0:     "PI_CUSTOM_ERR_0",
	C.PI_CUSTOM_ERR_999:   "PI_CUSTOM_ERR_999",
}

// ConvertErrorCodeToMessage returns a human-readable string based on the error code.
func ConvertErrorCodeToMessage(errorCode int, message string) error {
	errorMessage, exists := PiGPIOErrorMap[errorCode]
	if exists {
		return errors.Errorf("%s: %s", message, errorMessage)
	}
	return errors.Errorf("%s: %d", message, errorCode)
}
