// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IMUServiceClient is the client API for IMUService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IMUServiceClient interface {
	// AngularVelocity returns the most recent angular velocity reading from the given IMU.
	AngularVelocity(ctx context.Context, in *IMUServiceAngularVelocityRequest, opts ...grpc.CallOption) (*IMUServiceAngularVelocityResponse, error)
	// Orientation returns the most recent orientation reading from the given IMU.
	Orientation(ctx context.Context, in *IMUServiceOrientationRequest, opts ...grpc.CallOption) (*IMUServiceOrientationResponse, error)
}

type iMUServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMUServiceClient(cc grpc.ClientConnInterface) IMUServiceClient {
	return &iMUServiceClient{cc}
}

func (c *iMUServiceClient) AngularVelocity(ctx context.Context, in *IMUServiceAngularVelocityRequest, opts ...grpc.CallOption) (*IMUServiceAngularVelocityResponse, error) {
	out := new(IMUServiceAngularVelocityResponse)
	err := c.cc.Invoke(ctx, "/proto.api.component.v1.IMUService/AngularVelocity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMUServiceClient) Orientation(ctx context.Context, in *IMUServiceOrientationRequest, opts ...grpc.CallOption) (*IMUServiceOrientationResponse, error) {
	out := new(IMUServiceOrientationResponse)
	err := c.cc.Invoke(ctx, "/proto.api.component.v1.IMUService/Orientation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMUServiceServer is the server API for IMUService service.
// All implementations must embed UnimplementedIMUServiceServer
// for forward compatibility
type IMUServiceServer interface {
	// AngularVelocity returns the most recent angular velocity reading from the given IMU.
	AngularVelocity(context.Context, *IMUServiceAngularVelocityRequest) (*IMUServiceAngularVelocityResponse, error)
	// Orientation returns the most recent orientation reading from the given IMU.
	Orientation(context.Context, *IMUServiceOrientationRequest) (*IMUServiceOrientationResponse, error)
	mustEmbedUnimplementedIMUServiceServer()
}

// UnimplementedIMUServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIMUServiceServer struct {
}

func (UnimplementedIMUServiceServer) AngularVelocity(context.Context, *IMUServiceAngularVelocityRequest) (*IMUServiceAngularVelocityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AngularVelocity not implemented")
}
func (UnimplementedIMUServiceServer) Orientation(context.Context, *IMUServiceOrientationRequest) (*IMUServiceOrientationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Orientation not implemented")
}
func (UnimplementedIMUServiceServer) mustEmbedUnimplementedIMUServiceServer() {}

// UnsafeIMUServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMUServiceServer will
// result in compilation errors.
type UnsafeIMUServiceServer interface {
	mustEmbedUnimplementedIMUServiceServer()
}

func RegisterIMUServiceServer(s grpc.ServiceRegistrar, srv IMUServiceServer) {
	s.RegisterService(&IMUService_ServiceDesc, srv)
}

func _IMUService_AngularVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMUServiceAngularVelocityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUServiceServer).AngularVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.api.component.v1.IMUService/AngularVelocity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUServiceServer).AngularVelocity(ctx, req.(*IMUServiceAngularVelocityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMUService_Orientation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IMUServiceOrientationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMUServiceServer).Orientation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.api.component.v1.IMUService/Orientation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMUServiceServer).Orientation(ctx, req.(*IMUServiceOrientationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMUService_ServiceDesc is the grpc.ServiceDesc for IMUService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMUService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.api.component.v1.IMUService",
	HandlerType: (*IMUServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AngularVelocity",
			Handler:    _IMUService_AngularVelocity_Handler,
		},
		{
			MethodName: "Orientation",
			Handler:    _IMUService_Orientation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api/component/v1/imu.proto",
}
