service:
  golangci-lint-version: 1.51.x
run:
  go: 1.20
  deadline: 900s
  modules-download-mode: readonly
  skip-dirs-use-default: false
  skip-dirs:
    # TFlite uses FlatBuffer generated code that's ugly
    - ml/inference/tflite_metadata$
    - ml/inference/tflite$
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - goimports
    - golint
    - gomnd
    - ifshort
    - importas
    - inamedparam
    - interfacebloat
    - interfacer
    - ireturn
    - maintidx
    - makezero
    - maligned
    - musttag
    - nakedret
    - nestif
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(go.viam.com/rdk)
  gofumpt:
    lang-version: "1.19"
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
      - composites
  lll:
    line-length: 140
  revive:
    rules:
      - name: unused-parameter
        disabled: true
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupword
        - errcheck
        - exhaustive
        - goconst
        - gosec
    - path: /doc.go$
      linters:
        - lll
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
