service:
  golangci-lint-version: 1.46.x
run:
  deadline: 900s
  skip-dirs:
    - genfiles$
    - gen$
    - vendor$
    - test$
  tests: true
linters:
  enable-all: true
  disable:
    - containedctx
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - ifshort
    - interfacer
    - ireturn
    - maintidx
    - maligned
    - makezero
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - scopelint
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  gocritic:
    disabled-checks:
      - commentFormatting
  errcheck:
    check-blank: true
  gosec:
    excludes:
      - G601
  gci:
    sections:
      - standard
      - default
      - prefix(go.viam.com/rdk)
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  lll:
    line-length: 140
issues:
  exclude:
    - composites
  exclude-rules:
    - path: _test\.go$|^tests/|^samples/
      linters:
        - errcheck
        - contextcheck
        - exhaustive
        - forcetypeassert
        - goconst
        - gosec
        - govet
        - noctx
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
