service:
  golangci-lint-version: 1.61.x
run:
  timeout: 10m
  deadline: 900s
  modules-download-mode: readonly
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - execinquery
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - importas
    - inamedparam
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - musttag
    - nakedret
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter # TODO(go1.23): maybe reenable in the future but it's a big diff + buggy.
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(go.viam.com/rdk)
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
      - composites
  gosec:
    excludes:
      - G115 # TODO(go1.23): maybe reenable
  revive:
    # Unfortunately configuring a single rules disables all other rules, even
    # if we set `enable-all: true`
    #
    # To get around this, we include default rules:
    # https://github.com/mgechev/revive/blob/master/defaults.toml
    rules:
      - name: blank-imports
      - name: context-as-argument
        disabled: false
        arguments:
          - allowTypesBefore: "testing.TB,*testing.T,*testing.B,*testing.F"
      - name: context-keys-type
      - name: dot-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: var-declaration
      - name: var-naming
  lll:
    line-length: 140
  gocritic:
    disabled-checks:
      - ifElseChain
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupword
        - errcheck
        - exhaustive
        - goconst
        - gosec
    - path: /doc.go$
      linters:
        - lll
  exclude-use-default: false
  exclude-dirs-use-default: false
  max-per-linter: 0
  max-same-issues: 0
