# deps for our macos.yml CI job

brew "pkg-config"
brew "viamrobotics/brews/nlopt-static"
brew "x264"
brew "jpeg-turbo"
brew "ffmpeg"
# tflite needs to be last (why?)
brew "viamrobotics/brews/tensorflowlite"
