ARG MAIN_TAG=ghcr.io/viamrobotics/canon
ARG BASE_TAG=amd64

FROM $MAIN_TAG:$BASE_TAG as builder
COPY --chown=1000:1000 ./ /tmp/rdk
WORKDIR /tmp/rdk
RUN --mount=type=secret,id=netrc,uid=1000,dst=/home/testbot/.netrc sudo -Hu testbot bash -lc 'if [ `dpkg --print-architecture` = armhf ]; then \
        GOFLAGS=-tags=no_tflite make build-go tool-install; \
    else \
        make build-go lint-go; \
    fi'

FROM $MAIN_TAG:$BASE_TAG
COPY --from=builder --chown=1000:1000 /home/testbot/go /home/testbot/go
