FROM debian:latest

RUN apt update && DEBIAN_FRONTEND="noninteractive" apt install -y sudo

RUN useradd -m testbot
RUN echo 'testbot ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER testbot

COPY etc/setup.sh /tmp/setup.sh
RUN bash /tmp/setup.sh

RUN sudo rm -rf /home/testbot/.cache
RUN sudo apt clean

WORKDIR /home/testbot
ENTRYPOINT ["bash", "-lc"]
