ARG MAIN_TAG=ghcr.io/viamrobotics/canon
ARG BASE_TAG=amd64

FROM $MAIN_TAG:$BASE_TAG as builder
COPY --chown=1000:1000 ./ /tmp/rdk
WORKDIR /tmp/rdk
# `go mod download` first: `go build ./...` never fetches test-only deps, and the test jobs that
# run in this image expect a warm module cache.
RUN --mount=type=secret,id=netrc,uid=1000,dst=/home/testbot/.netrc sudo -Hu testbot bash -lc 'go mod download && make build-go tool-install'

FROM $MAIN_TAG:$BASE_TAG
COPY --from=builder --chown=1000:1000 /home/testbot/go /home/testbot/go
