ARG BASE_TAG=amd64

FROM ghcr.io/viamrobotics/canon:$BASE_TAG as builder
COPY --chown=1000:1000 ./ /tmp/rdk
RUN --mount=type=secret,id=netrc,uid=1000,dst=/home/testbot/.netrc sudo -u testbot bash -lc 'cd /tmp/rdk && make build-go'

FROM ghcr.io/viamrobotics/canon:$BASE_TAG
COPY --from=builder --chown=1000:1000 /home/testbot/go /home/testbot/go
COPY --from=builder --chown=1000:1000 /home/testbot/.cache /home/testbot/.cache
