// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DepthwiseConv2DOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsDepthwiseConv2DOptions(buf []byte, offset flatbuffers.UOffsetT) *DepthwiseConv2DOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DepthwiseConv2DOptions{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDepthwiseConv2DOptions(buf []byte, offset flatbuffers.UOffsetT) *DepthwiseConv2DOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DepthwiseConv2DOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DepthwiseConv2DOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DepthwiseConv2DOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DepthwiseConv2DOptions) Padding() Padding {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Padding(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DepthwiseConv2DOptions) MutatePadding(n Padding) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *DepthwiseConv2DOptions) StrideW() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DepthwiseConv2DOptions) MutateStrideW(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *DepthwiseConv2DOptions) StrideH() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DepthwiseConv2DOptions) MutateStrideH(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *DepthwiseConv2DOptions) DepthMultiplier() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DepthwiseConv2DOptions) MutateDepthMultiplier(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *DepthwiseConv2DOptions) FusedActivationFunction() ActivationFunctionType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return ActivationFunctionType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *DepthwiseConv2DOptions) MutateFusedActivationFunction(n ActivationFunctionType) bool {
	return rcv._tab.MutateInt8Slot(12, int8(n))
}

func (rcv *DepthwiseConv2DOptions) DilationWFactor() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *DepthwiseConv2DOptions) MutateDilationWFactor(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *DepthwiseConv2DOptions) DilationHFactor() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *DepthwiseConv2DOptions) MutateDilationHFactor(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func DepthwiseConv2DOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func DepthwiseConv2DOptionsAddPadding(builder *flatbuffers.Builder, padding Padding) {
	builder.PrependInt8Slot(0, int8(padding), 0)
}
func DepthwiseConv2DOptionsAddStrideW(builder *flatbuffers.Builder, strideW int32) {
	builder.PrependInt32Slot(1, strideW, 0)
}
func DepthwiseConv2DOptionsAddStrideH(builder *flatbuffers.Builder, strideH int32) {
	builder.PrependInt32Slot(2, strideH, 0)
}
func DepthwiseConv2DOptionsAddDepthMultiplier(builder *flatbuffers.Builder, depthMultiplier int32) {
	builder.PrependInt32Slot(3, depthMultiplier, 0)
}
func DepthwiseConv2DOptionsAddFusedActivationFunction(builder *flatbuffers.Builder, fusedActivationFunction ActivationFunctionType) {
	builder.PrependInt8Slot(4, int8(fusedActivationFunction), 0)
}
func DepthwiseConv2DOptionsAddDilationWFactor(builder *flatbuffers.Builder, dilationWFactor int32) {
	builder.PrependInt32Slot(5, dilationWFactor, 1)
}
func DepthwiseConv2DOptionsAddDilationHFactor(builder *flatbuffers.Builder, dilationHFactor int32) {
	builder.PrependInt32Slot(6, dilationHFactor, 1)
}
func DepthwiseConv2DOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
