// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FillOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsFillOptions(buf []byte, offset flatbuffers.UOffsetT) *FillOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FillOptions{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFillOptions(buf []byte, offset flatbuffers.UOffsetT) *FillOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FillOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FillOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FillOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func FillOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func FillOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
