// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type L2NormOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsL2NormOptions(buf []byte, offset flatbuffers.UOffsetT) *L2NormOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &L2NormOptions{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsL2NormOptions(buf []byte, offset flatbuffers.UOffsetT) *L2NormOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &L2NormOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *L2NormOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *L2NormOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *L2NormOptions) FusedActivationFunction() ActivationFunctionType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ActivationFunctionType(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *L2NormOptions) MutateFusedActivationFunction(n ActivationFunctionType) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func L2NormOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func L2NormOptionsAddFusedActivationFunction(builder *flatbuffers.Builder, fusedActivationFunction ActivationFunctionType) {
	builder.PrependInt8Slot(0, int8(fusedActivationFunction), 0)
}
func L2NormOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
