// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NegOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsNegOptions(buf []byte, offset flatbuffers.UOffsetT) *NegOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NegOptions{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsNegOptions(buf []byte, offset flatbuffers.UOffsetT) *NegOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NegOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *NegOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NegOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func NegOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func NegOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
