// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResizeBilinearOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsResizeBilinearOptions(buf []byte, offset flatbuffers.UOffsetT) *ResizeBilinearOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResizeBilinearOptions{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResizeBilinearOptions(buf []byte, offset flatbuffers.UOffsetT) *ResizeBilinearOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResizeBilinearOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ResizeBilinearOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResizeBilinearOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResizeBilinearOptions) AlignCorners() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ResizeBilinearOptions) MutateAlignCorners(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *ResizeBilinearOptions) HalfPixelCenters() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ResizeBilinearOptions) MutateHalfPixelCenters(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func ResizeBilinearOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ResizeBilinearOptionsAddAlignCorners(builder *flatbuffers.Builder, alignCorners bool) {
	builder.PrependBoolSlot(2, alignCorners, false)
}
func ResizeBilinearOptionsAddHalfPixelCenters(builder *flatbuffers.Builder, halfPixelCenters bool) {
	builder.PrependBoolSlot(3, halfPixelCenters, false)
}
func ResizeBilinearOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
