name: flex-checkout
description: "Check out branch head in PR target case, otherwise checkout local"
runs:
  using: composite
  steps:
  - if: github.event_name != 'pull_request_target'
    uses: actions/checkout@v4
  - if: github.event_name == 'pull_request_target'
    uses: actions/checkout@v4
    with:
      ref: ${{ github.event.pull_request.head.sha }}
