// Code generated by "stringer -type NodeState -trimprefix NodeState"; DO NOT EDIT.

package resource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeStateUnconfigured-0]
	_ = x[NodeStateConfiguring-1]
	_ = x[NodeStateReady-2]
	_ = x[NodeStateRemoving-3]
}

const _NodeState_name = "UnconfiguredConfiguringReadyRemoving"

var _NodeState_index = [...]uint8{0, 12, 23, 28, 36}

func (i NodeState) String() string {
	if i >= NodeState(len(_NodeState_index)-1) {
		return "NodeState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeState_name[_NodeState_index[i]:_NodeState_index[i+1]]
}
