Dir /host/etc/packaging/appimages/appimage-builder-cache/apt;
Dir::State /host/etc/packaging/appimages/appimage-builder-cache/apt;
Dir::Cache /host/etc/packaging/appimages/appimage-builder-cache/apt;
Dir::Etc::Main /host/etc/packaging/appimages/appimage-builder-cache/apt/apt.conf;
Dir::Etc::Parts /host/etc/packaging/appimages/appimage-builder-cache/apt/apt.conf.d;
Dir::Etc::SourceList /host/etc/packaging/appimages/appimage-builder-cache/apt/sources.list;
Dir::Etc::SourceListParts /host/etc/packaging/appimages/appimage-builder-cache/apt/sources.list.d;
Dir::Etc::PreferencesParts /host/etc/packaging/appimages/appimage-builder-cache/apt/preferences.d;
Dir::Etc::TrustedParts /host/etc/packaging/appimages/appimage-builder-cache/apt/keys;
Dir::State::status /host/etc/packaging/appimages/appimage-builder-cache/apt/dpkg/status;
Dir::Ignore-Files-Silently False;
APT::Install-Recommends False;
APT::Install-Suggests False;
APT::Immediate-Configure False;
APT::Architecture "arm64";
APT::Architectures {"arm64"; }
Acquire::Languages "none";
APT::Get::AllowUnauthenticated True;
Acquire::AllowInsecureRepositories True;
