// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite_metadata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RegexTokenizerOptions struct {
	_tab flatbuffers.Table
}

func GetRootAsRegexTokenizerOptions(buf []byte, offset flatbuffers.UOffsetT) *RegexTokenizerOptions {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RegexTokenizerOptions{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRegexTokenizerOptions(buf []byte, offset flatbuffers.UOffsetT) *RegexTokenizerOptions {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RegexTokenizerOptions{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RegexTokenizerOptions) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RegexTokenizerOptions) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RegexTokenizerOptions) DelimRegexPattern() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RegexTokenizerOptions) VocabFile(obj *AssociatedFile, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *RegexTokenizerOptions) VocabFileLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RegexTokenizerOptionsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RegexTokenizerOptionsAddDelimRegexPattern(builder *flatbuffers.Builder, delimRegexPattern flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(delimRegexPattern), 0)
}
func RegexTokenizerOptionsAddVocabFile(builder *flatbuffers.Builder, vocabFile flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(vocabFile), 0)
}
func RegexTokenizerOptionsStartVocabFileVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RegexTokenizerOptionsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
