package xarm

var servoErrorMap = map[byte]string{
	0x00: "xArm Servo: Joint Communication Error",
	0x0A: "xArm Servo: Current Detection Error",
	0x0B: "xArm Servo: Joint Overcurrent",
	0x0C: "xArm Servo: Joint Overspeed",
	0x0E: "xArm Servo: Position Command Overlimit",
	0x0F: "xArm Servo: Joints Overheat",
	0x10: "xArm Servo: Encoder Initialization Error",
	0x11: "xArm Servo: Single-turn Encoder Error",
	0x12: "xArm Servo: Multi-turn Encoder Error",
	0x13: "xArm Servo: Low Battery Voltage",
	0x14: "xArm Servo: Driver IC Hardware Error",
	0x15: "xArm Servo: Driver IC Init Error",
	0x16: "xArm Servo: Encoder Config Error",
	0x17: "xArm Servo: Large Motor Position Deviation",
	0x1A: "xArm Servo: Joint N Positive Overrun",
	0x1B: "xArm Servo: Joint N Negative Overrun",
	0x1C: "xArm Servo: Joint Commands Error",
	0x21: "xArm Servo: Drive Overloaded",
	0x22: "xArm Servo: Motor Overload",
	0x23: "xArm Servo: Motor Type Error",
	0x24: "xArm Servo: Driver Type Error",
	0x27: "xArm Servo: Joint Overvoltage",
	0x28: "xArm Servo: Joint Undervoltage",
	0x31: "xArm Servo: EEPROM RW Error",
	0x34: "xArm Servo: Initialization of Motor Angle Error",
}

var armBoxErrorMap = map[byte]string{
	0x01: "xArm: Emergency Stop Button Pushed In",
	0x02: "xArm: Emergency IO Triggered",
	0x03: "xArm: Emergency Stop 3-State Switch Pressed",
	0x0B: "xArm: Power Cycle Required",
	0x0C: "xArm: Power Cycle Required",
	0x0D: "xArm: Power Cycle Required",
	0x0E: "xArm: Power Cycle Required",
	0x0F: "xArm: Power Cycle Required",
	0x10: "xArm: Power Cycle Required",
	0x11: "xArm: Power Cycle Required",
	0x13: "xArm: Gripper Communication Error",
	0x15: "xArm: Kinematic Error",
	0x16: "xArm: Self Collision Error",
	0x17: "xArm: Joint Angle Exceeds Limit",
	0x18: "xArm: Speed Exceeds Limit",
	0x19: "xArm: Planning Error",
	0x1A: "xArm: Linux RT Error",
	0x1B: "xArm: Command Reply Error",
	0x1C: "xArm: End Module Communication Error",
	0x1D: "xArm: Other Errors",
	0x1E: "xArm: Feedback Speed Exceeds Limit",
	0x1F: "xArm: Collision Caused Abnormal Current",
	0x20: "xArm: Three-point Drawing Circle Calculation Error",
	0x21: "xArm: Abnormal Arm Current",
	0x22: "xArm: Recording Timeout",
	0x23: "xArm: Safety Boundary Limit",
	0x24: "xArm: Delay Command Limit Exceeded",
	0x25: "xArm: Abnormal Motion in Manual Mode",
	0x26: "xArm: Abnormal Joint Angle",
	0x27: "xArm: Abnormal Communication Between Power Boards",
}
var armBoxWarnMap = map[byte]string{
	0x0B: "xArm Warning: Buffer Overflow",
	0x0C: "xArm Warning: Command Parameter Abnormal",
	0x0D: "xArm Warning: Unknown Command",
	0x0E: "xArm Warning: Command No Solution",
}
