// eslint-disable-next-line unicorn/prefer-module
module.exports = {
  content: ['./src/**/*.{html,vue,js,ts}'],
  theme: {
    extend: {
      color: {
        viamBlue: '#045681',
        gray3: '#E4E4E6',
      },
      textColor: {
        'subtle-1': '#4E4F52',
        'subtle-2': '#555',
        default: '#282829',
        'gray-5': '#C5C6CC',
      },
      backgroundColor: {
        gray3: '#E4E4E6',
        'subtle-1': '#4E4F52',
      },
      fontFamily: {
        'space-grotesk': 'Space Grotesk',
      },
      maxHeight: {
        440: '440px',
      },
      height: {
        0.4: '40%',
      },
      screens: {
        laptop: '834px',
        tablet: '768px',
      },
      animation: {
        'pulse-grid': 'pulse 2s cubic-bezier(0.75, 0, 0.6, 1) infinite',
      },
      colors: {
        'text-heading': '#131414',
        'text-default': '#282829',
        'text-subtle-1': '#4e4f52',
        'text-subtle-2': '#7a7c80',
        'text-disabled': '#9c9ca4',
        'text-link': '#0066cc',
        black: '#131414',
        'gray-9': '#282829',
        'gray-8': '#4e4f52',
        'gray-7': '#7a7c80',
        'gray-6': '#9c9ca4',
        'gray-5': '#c5c6cc',
        'gray-4': '#d7d7d9',
        'gray-3': '#e4e4e6',
        'gray-2': '#edeef0',
        'gray-1': '#f7f7f8',
        'danger-fg': '#be3536',
        'danger-bg': '#fcecea',
        'danger-border': '#edc0bf',
        'warning-fg': '#a6570f',
        'warning-bg': '#fef3e0',
        'warning-bright': '#ddab3f',
        'warning-border': '#e9c89d',
        'success-fg': '#3d7d3f',
        'success-bg': '#e0fae3',
        'success-border': '#b9dcbc',
        'info-fg': '#0066cc',
        'info-bg': '#e1f3ff',
        'info-border': '#b6d1f4',
        'disabled-fg': '#9c9ca4',
        'disabled-bg': '#f2f2f4',
        'bg-1': '#ffffff',
        'bg-2': '#f7f7f8',
        'bg-3': '#f1f1f4',
        'border-1': '#e4e4e6',
        'border-2': '#d7d7d9',
        'text-highlight': '#e2f1fd',
      },
    },
  },
  plugins: [],
  safelist: ['list-disc', 'h-[400px]'],
};
