name: Build AppImage (Deploy)

on:
  workflow_call:
    inputs:
      date:
        required: true
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  appimage_deploy:
    name: AppImage Deploy
    runs-on: ubuntu-latest
    env:
      channel: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

    steps:
    - name: Authorize GCP
      uses: google-github-actions/auth@v1.1.1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Publish AppImage
      run: |
        gsutil mv "gs://packages.viam.com/apps/viam-server/testing/appimage/${{ inputs.date }}/${{ github.sha }}/*" "gs://packages.viam.com/apps/viam-server/"

    - name: Output Summary
      run: |
        echo "### Built AppImages for ${channel}" >> $GITHUB_STEP_SUMMARY
        echo "- arm64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-aarch64.AppImage" >> $GITHUB_STEP_SUMMARY
        echo "- x86_64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-x86_64.AppImage" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
