name: Buf Push

on:
  # Triggers the workflow on pushes to the main branch
  push:
    paths:
      - 'proto/**'
    branches:
      - main

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  buf-push:
    if: github.repository_owner == 'viamrobotics'
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.7.0
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}

  dispatch:
    needs: buf-push
    if: github.repository_owner == 'viamrobotics'
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64
    strategy:
      matrix:
        repo:
          - ['viamrobotics/python-sdk','viamrobotics/rust-sdk']
    steps:
      - name: Notify Proto Watchers
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: protos-updated
          client-payload: '{"repo_name": "${{github.repository}}", "sha": "${{github.sha}}"}'
