name: Test GCloud

on:
  workflow_dispatch:
  push:
    branches:
      - "debug-gcloud"

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Authorize GCP
      uses: otterverse/gcloud-auth@main
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        service_account: 'my-service-account@my-project.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: SSH
      uses: lhotari/action-upterm@v1
