name: Test GCloud

on:
  workflow_dispatch:
  push:
    branches:
      - "debug-gcloud"

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Fix Auth
      run: yes | gcloud auth login --cred-file="$GOOGLE_APPLICATION_CREDENTIALS"

    - name: SSH
      uses: lhotari/action-upterm@v1
