name: full-static (Deploy)

on:
  workflow_call:
    inputs:
      date:
        required: true
        type: string
      channel:
        required: true
        type: string
      version:
        required: false
        type: string
    secrets:
      GCP_CREDENTIALS:
        required: true

jobs:
  full-static-deploy:
    runs-on: ubuntu-latest
    env:
      BUCKET: packages.viam.com/apps/viam-server
      GOARCHES: amd64 arm64 arm
    steps:
    - name: Authorize GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Publish full-static binaries
      run: |
        gsutil mv "gs://${{ env.BUCKET }}/testing/full-static/${{ inputs.date }}/${{ github.sha }}/*" "gs://${{ env.BUCKET }}/"

    - name: URLs to summary
      shell: bash
      run: |
        echo "### Published full-static binaries for ${{ inputs.channel }}" >> $GITHUB_STEP_SUMMARY
        for arch in amd64 arm64 arm; do
          echo "- $arch https://storage.googleapis.com/${{ env.BUCKET }}/viam-server-${{ inputs.channel }}-static-$arch" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ inputs.version }}" ]; then
            echo "- $arch https://storage.googleapis.com/${{ env.BUCKET }}/viam-server-${{ inputs.channel }}-${{ inputs.version }}-static-$arch" >> $GITHUB_STEP_SUMMARY
          fi
        done
