name: Motion Update

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths:
      - 'motionplan/**'
      - 'referenceframe/**'
      - 'spatialmath/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  motion_benchmarks:
    uses: viamrobotics/rdk/.github/workflows/motion-benchmarks.yml@DATA-859-motion-integration-tests
