name: Motion Quality Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  test_motion_quality:
    name:  Motion Quality Tests
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 30
    steps:
    - name: Check out main branch code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2

    - name: Check out code in motion-testing directory
      uses: actions/checkout@v3
      with:
        repository: viamrobotics/motion-testing
        ref: upgrade-rdk
        path: motion-testing

    - name: Run motion benchmark
      run: |
        sudo -u testbot bash -lc 'cd motion-testing && ./compile.sh && sudo go test ./... -v -run TestIntegration'
