name: Motion Integration Test

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_motion_integration:
    name:  Test Motion Integration
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 30
    steps:
    - name: Check out main branch code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2

