name: Motion Extended Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      skip:
        description: 'Skip motion tests. Set by check-changes in test.yml when no motion-related files are detected in the diff.'
        type: boolean
        default: false

jobs:
  motion-tests-extended:
    name:  Motion Extended Tests
    runs-on: ubuntu-16-core
    container: ghcr.io/viamrobotics/rdk-devenv:amd64-cache
    if: ${{ !inputs.skip }}
    timeout-minutes: 30
    steps:

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Check out code in motion-testing repository
      uses: actions/checkout@v4
      with:
        repository: viamrobotics/motion-testing
        path: motion-testing

    - name: Change ownership to testbot
      run: chown -R testbot:testbot .

    - name: Run motion tests on PR branch
      shell: bash
      env:
        URL: ${{ github.event.pull_request.head.repo.html_url }}
        SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "Skipping actual running of extended motion tests until RSDK-10651 has been resolved"
        # cd motion-testing
        # go mod edit -replace go.viam.com/rdk=${URL#"https://"}@$SHA
        # sudo -Hu testbot bash -lc "go mod tidy && go test ./... -v -run TestMotionExtended"
