# See https://github.com/mvdan/github-actions-golang for golang nuances
name: Package Viam-Server

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/Dockerfile.fortest'
      - '**/.github/workflows/docker.yml'

env:
  GOPRIVATE: "github.com/viamrobotics/*,go.viam.com/*"

jobs:
  build_and_pack:
    name: Build and Pack Server
    runs-on: Pi4

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Configure git for private modules
      run: |
        git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Build server package
      env:
        DEBEMAIL: james@viam.com
        DEBFULLNAME: Viam Buildbot/James Otting
      run: |
        make deb-server

    - name: Add package to repo
      run: |
        dput local etc/packaging/work/*.changes

    - name: Sync repo to cloud
      run: |
        gsutil -m rsync -d -r /home/buildbot/debian/viam gs://packages.viam.com/debian/viam
        gsutil -m setmeta -h "Cache-Control: no-cache" 'gs://packages.viam.com/debian/viam/[A-Z]*'
