# See https://github.com/mvdan/github-actions-golang for golang nuances
name: Package Server for Debian

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/Dockerfile.fortest'
      - '**/.github/workflows/docker.yml'
  pull_request:
    branches: [ master ]

env:
  GOPRIVATE: "github.com/viamrobotics/*,go.viam.com/*"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: Pi4

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      run: |
        git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"

    - name: Build Server
      run: |
        make server

