name: Pull Request Update

concurrency: 
  group: pullrequest-trusted-${{ github.head_ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'main' ]

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  eslint:
    timeout-minutes: 5
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    steps:
    - uses: actions/checkout@v2
    - name: Install modules & generate protos
      run: make buf-web
    - name: Run ESLint
      run: make lint-web

  typecheck:
    name: Typescript
    timeout-minutes: 5
    runs-on: [self-hosted, x64]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    steps:
    - uses: actions/checkout@v2
    - name: Install modules & generate protos
      run: make buf-web
    - name: Run Typecheck
      run: make typecheck-web
