name: Release Stable

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - 'SMURFv[0-9]+.[0-9]+.[0-9]+'

env:
  RELEASE_TYPE: 'stable'

# To test workflow updates you need to work in a branch directly on viamrobotics/rdk
# and tag your working branch instead of @main in any viamrobotics/rdk "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: viamrobotics/rdk/.github/workflows/test.yml@rc-workflows
    secrets:
      MONGODB_TEST_OUTPUT_URI: ${{ secrets.MONGODB_TEST_OUTPUT_URI }}

  appimage:
    needs: test
    uses: viamrobotics/rdk/.github/workflows/appimage.yml@rc-workflows
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  staticbuild:
    needs: test
    uses: viamrobotics/rdk/.github/workflows/staticbuild.yml@rc-workflows
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  slack-workflow-status:
    if: ${{ failure() }}
    name: Post Workflow Status To Slack
    needs:
      - test
      - appimage
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          channel: '#team-devops'
          name: 'Workflow Status'
