name: Test Binaries Cleanup

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '37 7 15 * *' # once a month (15th) at 07:37 UTC (2:37AM/EST, 3:37AM/EDT)
  workflow_dispatch:

jobs:
  clean_binaries:
    name: Clean Test Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Authorize GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Remove Failed Test Binaries
      run: |
        gsutil -m rm -r "gs://packages.viam.com/apps/viam-server/testing/`date +%Y-%m -d 'last month'`*" || true

  slack-workflow-status:
    name: Post Workflow Status To Slack
    needs: [clean_binaries]
    if: failure()
    permissions:
      actions: read
    uses: ./.github/workflows/slack-failure.yml
    secrets: inherit
