// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite_metadata

import "strconv"

type BoundingBoxType int8

const (
	BoundingBoxTypeUNKNOWN    BoundingBoxType = 0
	BoundingBoxTypeBOUNDARIES BoundingBoxType = 1
	BoundingBoxTypeUPPER_LEFT BoundingBoxType = 2
	BoundingBoxTypeCENTER     BoundingBoxType = 3
)

var EnumNamesBoundingBoxType = map[BoundingBoxType]string{
	BoundingBoxTypeUNKNOWN:    "UNKNOWN",
	BoundingBoxTypeBOUNDARIES: "BOUNDARIES",
	BoundingBoxTypeUPPER_LEFT: "UPPER_LEFT",
	BoundingBoxTypeCENTER:     "CENTER",
}

var EnumValuesBoundingBoxType = map[string]BoundingBoxType{
	"UNKNOWN":    BoundingBoxTypeUNKNOWN,
	"BOUNDARIES": BoundingBoxTypeBOUNDARIES,
	"UPPER_LEFT": BoundingBoxTypeUPPER_LEFT,
	"CENTER":     BoundingBoxTypeCENTER,
}

func (v BoundingBoxType) String() string {
	if s, ok := EnumNamesBoundingBoxType[v]; ok {
		return s
	}
	return "BoundingBoxType(" + strconv.FormatInt(int64(v), 10) + ")"
}
