// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite_metadata

import "strconv"

type CoordinateType int8

const (
	CoordinateTypeRATIO CoordinateType = 0
	CoordinateTypePIXEL CoordinateType = 1
)

var EnumNamesCoordinateType = map[CoordinateType]string{
	CoordinateTypeRATIO: "RATIO",
	CoordinateTypePIXEL: "PIXEL",
}

var EnumValuesCoordinateType = map[string]CoordinateType{
	"RATIO": CoordinateTypeRATIO,
	"PIXEL": CoordinateTypePIXEL,
}

func (v CoordinateType) String() string {
	if s, ok := EnumNamesCoordinateType[v]; ok {
		return s
	}
	return "CoordinateType(" + strconv.FormatInt(int64(v), 10) + ")"
}
