// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tflite_metadata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StatsT struct {
	Max []float32
	Min []float32
}

func (t *StatsT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	maxOffset := flatbuffers.UOffsetT(0)
	if t.Max != nil {
		maxLength := len(t.Max)
		StatsStartMaxVector(builder, maxLength)
		for j := maxLength - 1; j >= 0; j-- {
			builder.PrependFloat32(t.Max[j])
		}
		maxOffset = builder.EndVector(maxLength)
	}
	minOffset := flatbuffers.UOffsetT(0)
	if t.Min != nil {
		minLength := len(t.Min)
		StatsStartMinVector(builder, minLength)
		for j := minLength - 1; j >= 0; j-- {
			builder.PrependFloat32(t.Min[j])
		}
		minOffset = builder.EndVector(minLength)
	}
	StatsStart(builder)
	StatsAddMax(builder, maxOffset)
	StatsAddMin(builder, minOffset)
	return StatsEnd(builder)
}

func (rcv *Stats) UnPackTo(t *StatsT) {
	maxLength := rcv.MaxLength()
	t.Max = make([]float32, maxLength)
	for j := 0; j < maxLength; j++ {
		t.Max[j] = rcv.Max(j)
	}
	minLength := rcv.MinLength()
	t.Min = make([]float32, minLength)
	for j := 0; j < minLength; j++ {
		t.Min[j] = rcv.Min(j)
	}
}

func (rcv *Stats) UnPack() *StatsT {
	if rcv == nil {
		return nil
	}
	t := &StatsT{}
	rcv.UnPackTo(t)
	return t
}

type Stats struct {
	_tab flatbuffers.Table
}

func GetRootAsStats(buf []byte, offset flatbuffers.UOffsetT) *Stats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Stats{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStats(buf []byte, offset flatbuffers.UOffsetT) *Stats {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Stats{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Stats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Stats) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Stats) Max(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Stats) MaxLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Stats) MutateMax(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *Stats) Min(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *Stats) MinLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Stats) MutateMin(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func StatsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StatsAddMax(builder *flatbuffers.Builder, max flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(max), 0)
}
func StatsStartMaxVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatsAddMin(builder *flatbuffers.Builder, min flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(min), 0)
}
func StatsStartMinVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func StatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
